<?php
return [
    'reservation' => [
        'name' => 'reservation',
        'slug' => 'reservation',
        'type' => 'module',
        'status' => 'on',
        'is_pro' => false,
        'title' => __('Reservation', 'wpcafe'),
        'description' => __('Allows customers to book tables online for specific dates and times, giving you full control over your restaurant’s schedule.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => '',
        'icon' => wpc_get_addons_icon_url('reservation'),
    ],
    'food_ordering' => [
        'name' => 'food_ordering',
        'slug' => 'food_ordering',
        'type' => 'module',
        'status' => 'on',
        'is_pro' => false,
        'title' => __('Food Ordering', 'wpcafe'),
        'description' => __('Enables customers to place online orders for your food and drinks directly from your website, integrating with WooCommerce for seamless checkout.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => '',
        'icon' => wpc_get_addons_icon_url('food-order'),
    ],
    'location' => [
        'name' => 'location',
        'slug' => 'location',
        'type' => 'module',
        'status' => 'on',
        'is_pro' => false,
        'title' => __('Location', 'wpcafe'),
        'description' => __('Helps you manage multiple restaurant branches and allows customers to see menus and services specific to each location.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => '',
        'icon' => wpc_get_addons_icon_url('location'),
    ],
    'table_layout' => [
        'name' => 'table_layout',
        'slug' => 'table_layout',
        'type' => 'module',
        'parent' => 'reservation',
        'status' => $table_layout_status,
        'is_pro' => true,
        'title' => __('Table Layout', 'wpcafe'),
        'description' => __('Provides a visual table layout for your restaurant, letting customers select their preferred table when making a reservation.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/reservation/table-selection-layout/',
        'icon' => wpc_get_addons_icon_url('table-layout'),
    ],
    'delivery' => [
        'name' => 'delivery',
        'slug' => 'delivery',
        'type' => 'module',
        'parent' => 'food_ordering',
        'status' => $delivery_module_status,
        'is_pro' => true,
        'title' => __('Delivery', 'wpcafe'),
        'description' => __('Manage and automate your food delivery service, including setting up delivery areas, times, and fees.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '/wp-admin/admin.php?page=wpcafe#/settings?tab=delivery',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/food-ordering/delivery/',
        'icon' => wpc_get_addons_icon_url('delivery'),
    ],
    'pickup' => [
        'name' => 'pickup',
        'slug' => 'pickup',
        'type' => 'module',
        'parent' => 'food_ordering',
        'status' => 'off',
        'is_pro' => true,
        'title' => __('Pickup', 'wpcafe'),
        'description' => __('Set up and manage food pickup options for your customers, allowing them to place orders online and collect them in-store.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '/wp-admin/admin.php?page=wpcafe#/settings?tab=pickup',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/food-ordering/pickup/',
        'icon' => wpc_get_addons_icon_url('pickup'),
    ],
    'tipping' => [
        'name' => 'tipping',
        'slug' => 'tipping',
        'type' => 'module',
        'parent' => 'food_ordering',
        'status' => 'off',
        'is_pro' => false,
        'title' => __('Tipping', 'wpcafe'),
        'description' => __('Allows customers to add a tip for your staff during checkout, giving you a way to increase revenue.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '/wp-admin/admin.php?page=wpcafe#/settings?tab=tipping',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/food-ordering/tipping/',
        'icon' => wpc_get_addons_icon_url('tipping'),
    ],
    'discount' => [
        'name' => 'discount',
        'slug' => 'discount',
        'type' => 'module',
        'parent' => 'food_ordering',
        'status' => 'off',
        'is_pro' => true,
        'title' => __('Discount', 'wpcafe'),
        'description' => __('Create and manage various discount offers and coupons for your menu items, encouraging more sales and repeat customers.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '/wp-admin/admin.php?page=wpcafe#/discount',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/food-ordering/discount-2/',
        'icon' => wpc_get_addons_icon_url('discount'),
    ],
    'timed-product' => [
        'name' => 'timed-product',
        'slug' => 'timed-product',
        'type' => 'module',
        'parent' => 'food_ordering',
        'status' => 'off',
        'is_pro' => true,
        'title' => __('Timed Product', 'wpcafe'),
        'description' => __('Lets you set up special menus or products that are only available for ordering during specific times of the day.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '/wp-admin/admin.php?page=wpcafe#/timed-product',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/food-ordering/how-to-set-up-time-based-food-menus-in-wpcafe/',
        'icon' => wpc_get_addons_icon_url('timed-product'),
    ],
    'mini_cart' => [
        'name' => 'mini_cart',
        'slug' => 'mini_cart',
        'type' => 'module',
        'parent' => 'food_ordering',
        'status' => 'off',
        'is_pro' => false,
        'title' => __('Mini Cart', 'wpcafe'),
        'description' => __('Adds a floating mini-cart widget to your website, allowing customers to view and manage their order without leaving the page.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '/wp-admin/admin.php?page=wpcafe#/settings?tab=mini-cart',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/food-ordering/minicart-2/',
        'icon' => wpc_get_addons_icon_url('mini-cart'),
    ],
    'receipt-layout' => [
        'name' => 'receipt-layout',
        'slug' => 'receipt-layout',
        'type' => 'module',
        'parent' => 'food_ordering',
        'status' => 'off',
        'is_pro' => true,
        'title' => __('Receipt Layout', 'wpcafe'),
        'description' => __('Customize the layout and design of your order receipts for a professional and branded look.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/food-ordering/how-to-set-up-receipt-layouts-in-wpcafe/',
        'icon' => wpc_get_addons_icon_url('receipt-layout'),
    ],
];