<?php
return [
    'fluent-crm' => [
        'name' => 'fluent-crm',
        'slug' => 'fluent-crm',
        'type' => 'integration',
        'status' => 'on',
        'is_pro' => false,
        'title' => __('Fluent CRM', 'wpcafe'),
        'description' => __('Connect with Fluent CRM to manage customer data and automate email marketing from your dashboard.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/integrations/wpc-fluentcrm-integration/',
        'icon' => wpc_get_addons_icon_url('fluent-crm'),
    ],
    'zapier' => [
        'name' => 'zapier',
        'slug' => 'zapier',
        'type' => 'integration',
        'status' => 'on',
        'is_pro' => true,
        'title' => __('Zapier', 'wpcafe'),
        'description' => __('Automate workflows by connecting with thousands of apps like Google Sheets and Slack.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/integrations/zapier-integration/',
        'icon' => wpc_get_addons_icon_url('zapier'),
    ],
    'pabbly' => [
        'name' => 'pabbly',
        'slug' => 'pabbly',
        'type' => 'integration',
        'status' => 'on',
        'is_pro' => true,
        'title' => __('Pabbly', 'wpcafe'),
        'description' => __('Integrate with Pabbly to automate business tasks and manage email marketing efficiently.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/integrations/pabbly-integration/',
        'icon' => wpc_get_addons_icon_url('pabbly'),
    ],
    'twilio' => [
        'name' => 'twilio',
        'slug' => 'twilio',
        'type' => 'integration',
        'status' => 'on',
        'is_pro' => true,
        'title' => __('Twilio', 'wpcafe'),
        'description' => __('Enable real-time SMS notifications for new orders and reservations, improving communication with customers.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/integrations/twilio-sms-integration/',
        'icon' => wpc_get_addons_icon_url('twilio'),
    ],
    'thermal-printer' => [
        'name' => 'thermal-printer',
        'slug' => 'thermal-printer',
        'type' => 'integration',
        'status' => 'on',
        'is_pro' => true,
        'title' => __('Thermal Printer', 'wpcafe'),
        'description' => __('Print order receipts and tickets directly to a thermal printer, streamlining your kitchen operations.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/integrations/thermal-printer-integration/',
        'icon' => wpc_get_addons_icon_url('thermal-printer'),
    ],
    'clover-pos' => [
        'name' => 'clover-pos',
        'slug' => 'clover-pos',
        'type' => 'integration',
        'status' => 'on',
        'is_pro' => true,
        'title' => __('Clover POS', 'wpcafe'),
        'description' => __('Connect online orders with your Clover POS system for centralized sales and inventory management.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/integrations/woocommerce-clover-pos-integration/',
        'icon' => wpc_get_addons_icon_url('clover-pos'),
    ],
    'google-map' => [
        'name' => 'google-map',
        'slug' => 'google-map',
        'type' => 'integration',
        'status' => 'on',
        'is_pro' => true,
        'title' => __('Google Map', 'wpcafe'),
        'description' => __('Helps you accurately set and display the precise location of your restaurant branches on a map, making it easy for customers to find your business.', 'wpcafe'),
        'notice' => '',
        'demo_link' => '',
        'settings_link' => '',
        'doc_link' => 'https://support.themewinter.com/docs/plugins/plugin-docs/delivery-module/store-added-in-google-maps/',
        'icon' => wpc_get_addons_icon_url('google-map'),
    ],
];